#!/bin/bash
./mem2.bash&pid0=$!
rm res12.csv
rm top5_12.csv
echo "Line, free, swap" >> res12.csv
while :; do
	line=$(top -p $pid0 -b -n 1 | head -8 | tail -n +8)
	free=$(top -b -n 1 | head -4 | tail -n +4 | awk '{print ""$6""}')
	swap=$(top -b -n 1 | head -5 | tail -n +5 | awk '{print ""$5""}')
	line=$(echo -e $line | awk '{print ""$11", "$10", "$5", "$6", "$7", "$9""}')
	line=$(echo -e "$line, $free, $swap")
	top5=$(top -b -n 1 | head -12 | tail -n +8 | awk '{print ""$1""}' | paste -s -d ",") 
	echo $top5 >> top5_12.csv
	echo $line >> res12.csv
done 
