#!/bin/bash
./mem.bash&pid0=$!
rm res11.csv
echo "Time, mem, Virt, Res, SHR, CPU, free, swap" >> res11.csv
while :; do
	line=$(top -p $pid0 -b -n 1 | head -8 | tail -n +8)
	free=$(top -b -n 1 | head -4 | tail -n +4 | awk '{print ""$6""}')
	swap=$(top -b -n 1 | head -5 | tail -n +5 | awk '{print ""$5""}')
	line=$(echo -e $line | awk '{print ""$11", "$10", "$5", "$6", "$7", "$9""}')
	line=$(echo -e "$line, $free, $swap")
	echo $line >> res11.csv
done 
